site_name: PKT Documentation
site_url: https://docs.pkt.cash/
site_author: PKT
site_description: ""
repo_url: "https://github.com/pkt-cash/pkt-docs"

plugins:
  - search

theme:
  name: null
  custom_dir: custom_theme
  fluid_layout: false


nav:
  - Home: index.md
  - Learn:
    - What is PKT?: learn/pkt.md
    - What is PacketCrypt?: learn/packetcrypt.md
    - What is PKT Cash?: learn/pkt-cash.md
    - What is WPKT?: learn/wpkt.md
    - What is the Network Steward?: learn/network-steward.md
    - Whitepapers: https://pkt.cash/PKT_Network_v1.0_2021.02.01.pdf
  - Wallet Setup:
    - How to setup a PKT Wallet: wallet_setup/pkt-wallet-setup.md
    - Installing from Seed: wallet_setup/install-from-seed.md
    - Installing PKT Electrum (Mac/Windows): wallet_setup/install-pkt-electrum.md
    - Installing PKT.World Wallet (Mac/Windows): wallet_setup/pkt-world-wallet.md
    - Installing PKT Zulu Wallet (Mac): wallet_setup/pkt-zulu-wallet.md
    - Installing PKT CLI Wallet (Mac/Windows/Linux): wallet_setup/pkt-cli-wallet.md
  - Start Mining:
    - Intro to PKT Mining: start_mining/intro.md
    - How to Start Announcement Mining: start_mining/announcement-mining.md
    - How to Setup a PKT Mining Pool: start_mining/pkt-mining-pool.md
  - Advanced Learning:
    - How to Run a Pktd Full Node: adv_learning/pktd-full-node.md
    - How to Swap PKT and Wrapped PKT: adv_learning/swap-pkt-wrapped-pkt.md
  - Community:
    - Code of Conduct: code_of_conduct.md
    - Ethical Communication Guidelines: community/ethica-communication-guidelines.md
    - Classifieds: community/classifieds.md
    - Press & Media Assets: community/press-media-assets.md


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - pymdownx.extra

extra_css:
    - css/extra.css