site_name: PKT Documentation
site_url: https://docs.pkt.cash/
site_author: PKT
site_description: ""
repo_url: "https://github.com/pkt-cash/pkt-docs"

theme:
  name: null
  custom_dir: pkt
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md
  - PKT Electrum: electrum/index.md
  - Mining: mining/index.md
  - Pool Operation: mining/pool_setup_guide.md
  - Pktd: pktd/index.md
  - PKTWallet: pktd/pktwallet.md
  - Wrapped PKT: wrapped_pkt.md
  - Electrum Import: pktd/migrating_from_electrum.md
  - FAQ: PKT_FAQ.md
  - Code of Conduct: code_of_conduct.md
  - Commercial: commercial.md
  - Useful Tools: useful_tools.md
  - Communication: communication.md
  - Units & Fees: units.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
